import type { BroadcastTemplate } from '@/shared/preview/templateContract'
import phone_bg from '@/assets/bg/PA_phone_bg.png'

export const phoneCallTemplate: BroadcastTemplate = {
    id: 'phone-call',
    name: 'Phone Call Lower Third',
    canvas: {
        width: 1920,
        height: 1080,
        background: {
            type: 'image',
            value: phone_bg,
            objectFit: 'contain',
        },
    },
    layers: [
        {
            id: 'phone-call-photo-frame',
            type: 'shape',
            shapeType: 'rect',
            x: 159,
            y: 220,
            width: 411,
            height: 511,
            zIndex: 1,
            fill: {
                type: 'solid',
                value: 'transparent',
            },
            borderRadius: 4,
        },
        {
            id: 'phone-call-person-image',
            type: 'image',
            x: 161,
            y: 218,
            width: 411,
            height: 511,
            zIndex: 2,
            src: '{image}',
            objectFit: 'cover',
        },
        {
            id: 'phone-call-label-panel',
            type: 'shape',
            shapeType: 'rect',
            x: 436,
            y: 814,
            width: 135,
            height: 32,
            zIndex: 3,
            fill: {
                type: 'solid',
                value: '#c70018',
            },
            borderRadius: 2,
        },
        {
            id: 'phone-call-lower-third',
            type: 'shape',
            shapeType: 'rect',
            x: 575,
            y: 858,
            width: 1292,
            height: 120,
            zIndex: 3,
            fill: {
                type: 'solid',
                value: '#fff',
            },
            borderRadius: 2,
        },
        {
            id: 'phone-call-name-text',
            type: 'text',
            x: 609,
            y: 874,
            width: 1020,
            height: 52,
            zIndex: 5,
            fieldId: 'name',
            fallbackText: 'NUME PERSOANA',
            fitInBox: true,
            fitMode: 'scaleX',
            minScaleX: 0.6,
            textStyle: {
                fontFamily: 'inherit',
                fontSize: 30,
                fontWeight: 800,
                color: '#111111',
                align: 'left',
                lineHeight: 1,
                transform: 'uppercase',
            },
        },
        {
            id: 'phone-call-occupation-text',
            type: 'text',
            x: 607,
            y: 923,
            width: 1040,
            height: 40,
            zIndex: 5,
            fieldId: 'occupation',
            fallbackText: 'Functie Persoana',
            fitInBox: true,
            fitMode: 'scaleX',
            minScaleX: 0.65,
            textStyle: {
                fontFamily: 'inherit',
                fontSize: 30,
                fontWeight: 600,
                color: '#111111',
                align: 'left',
                lineHeight: 1,
            },
        },
    ],
}
